version: '3'

services:
  app:
    build:
      context: .  # It means use the buld from current directory
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"      
